USE [master]
GO

CREATE DATABASE [TESTE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TESTE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TESTE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TESTE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TESTE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO


USE [TESTE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONTAS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CONTAS](
	[COD_CONTA] [int] IDENTITY(100,1) NOT NULL,
	[NOME] [varchar] (255) COLLATE Latin1_General_CI_AS NOT NULL,
	[SALDO] [float] NOT NULL
 CONSTRAINT [PK_COD_CONTA] PRIMARY KEY CLUSTERED 
(
	[COD_CONTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/*
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[CONTAS] TO [DBO] AS [dbo]
GO*/





SELECT * FROM [CONTAS]

INSERT INTO [CONTAS] VALUES ('tes', 500.55)

/*
UPDATE [CONTAS] WITH(ROWLOCK) SET SALDO = SALDO + (-500)  

UPDATE CONTAS SET SALDO = SALDO + (100) WHERE COD_CONTA = 500

DELETE FROM [CONTAS] 
*/
